django/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.chat_page, name='home'),
    path('create_room/', views.create_room, name='create_room'),
	path('send_game_invite/', views.send_game_invite, name='send_game_invite'),
    path('<str:slug>/', views.room, name='room'),
]

django/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

from game import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include('game.urls')),
    path('', include('home.urls')),
    path('chat/', include('chat.urls')),
    path('users/', include('users.urls')),
    path('', include('security.urls')),
    path("partial-rendering/", views.partial_rendering),
]

# to access user uploaded images (profile picture)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_v, name='signup'),
    path('blocking/', views.blocking, name='blocking'),
    path('login/', views.login_v, name='login'),
    path('callback/', views.callback, name='callback'),
    path('logout/', views.logout_v, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile/<str:username>', views.profile, name='profile'),
	path('profile/edit/', views.editprofile, name='profile_edit'),
    path('profile/<str:username>/delete/', views.deleteprofile, name='profile_delete'),
    path('friend_request/', views.send_friend_request, name='friend_request'),
    path('friend_remove/', views.remove_friend, name='remove_friend'),
    path('cancel_friend_request/', views.cancel_friend_request, name='friend_request_cancel'),
    path('accept_friend_request/<str:friend_request_id>', views.accept_friend_request, name='friend_request_accept'),
    path('decline_friend_request/<str:friend_request_id>', views.decline_friend_request, name='friend_request_decline'),
]

django/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from PIL import Image
from django.conf import settings
from django.utils import timezone
from .helpers import pick_random_description

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pics')
    isstudent = models.BooleanField(default=False)
    wins = models.IntegerField(default=0)
    losses = models.IntegerField(default=0)
    creation_date = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=False)
    description = models.CharField(default=pick_random_description())
    blocklist = models.ManyToManyField(User, blank=True, related_name="blocklist")

    def __str__(self):
        return f'{self.user.username} Profile'
    
    # resizes all large profile images
    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

class FriendList(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user")
    friends = models.ManyToManyField(User, blank=True, related_name="friends")

    def __str__(self):
        return self.user.username
    
    def add_friend(self, account):
        """
        Add a new friend
        """
        if account not in self.friends.all():
            self.friends.add(account)
            self.save()
    
    def remove_friend(self, account):
        """
        Remove friend
        """
        if account in self.friends.all():
            self.friends.remove(account)
    
    def unfriend(self, target):
        """
        Unfriend someone
        """
        my_friends_list = self # person terminating 
        my_friends_list.remove_friend(target)

        targets_friends_list = FriendList.objects.get(user=target)
        targets_friends_list.remove_friend(self.user)

    def is_mutual_friend(self, target):
        """
        Is this a friend
        """
        if target in self.friends.all():
            return True
        return False

class FriendRequest(models.Model):
    """
    A friend request consists of two main parts:
        1. SENDER:
            - Person sending the friend request
        2. RECEIVER:
            - Person receiving the friend request
    """
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="receiver")
    is_active = models.BooleanField(blank=True, null=False, default=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sender.username
    
    def accept(self):
        """
        Accept a friend request
            Update both SENDER and RECEIVER friend lists
        """
        receiver_friend_list = FriendList.objects.get(user=self.receiver)
        if receiver_friend_list:
            receiver_friend_list.add_friend(self.sender)
            sender_friend_list = FriendList.objects.get(user=self.sender)
            if sender_friend_list:
                sender_friend_list.add_friend(self.receiver)
                self.is_active = False
                self.save()
    
    def decline(self):
        """
        Decline a friend request (sent to you)
            Is it "declined" by setting the "is_active" field to False
        """
        self.is_active = False
        self.save()
    
    def cancel(self):
        """
        Cancel a friend request (you sent)
            It is "cancelled" by setting the "is_active" field to False
        """
        self.is_active = False
        self.save()

django/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

django/users/views.py
import os, json
from urllib.parse import urlencode
from dotenv import load_dotenv
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .models import FriendList, FriendRequest
from .utils import Oauth42, get_friend_request_or_false
from .friend_request_status import FriendRequestStatus
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.decorators.http import require_GET, require_POST
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse, HttpResponseBadRequest
from django.urls import reverse
from django.template.loader import render_to_string
from render_block import render_block_to_string
from django.middleware.csrf import get_token
from game.models import LeaderboardEntry
#fred
from dataclasses import dataclass
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_GET
from django.views.decorators.http import require_http_methods
from django.views.decorators.http import require_POST
from faker import Faker
from django_htmx.middleware import HtmxDetails
from django.core.paginator import Paginator
from django_htmx.http import HttpResponseClientRedirect,push_url

# Typing pattern recommended by django-stubs:
# https://github.com/typeddjango/django-stubs#how-can-i-create-a-httprequest-thats-guaranteed-to-have-an-authenticated-user
class HtmxHttpRequest(HttpRequest):
    htmx: HtmxDetails
    
import logging
# logger = logging.getLogger(__name__)
logger = logging.getLogger("users")
#fred

# Load environment variables
load_dotenv()

CLIENT_ID = os.getenv('CLIENT_ID')
CLIENT_SECRET = os.getenv('CLIENT_SECRET')
REDIRECT_URI = 'https://localhost/users/callback/'

# Define the FROMLOGIN and FROMSIGNUP variables
FROMLOGIN = 'd56b699830e77ba53855679cb1d252da'
FROMSIGNUP = '7d2abf2d0fa7c3a0c13236910f30bc43'

def build_authorize_uri(state_value):
    logger.debug("== build_authorize_uri")
    params = {
        'client_id': CLIENT_ID,
        'redirect_uri': REDIRECT_URI,
        'response_type': 'code',
        'scope': 'public',
        'state': state_value
    }
    return f"https://api.intra.42.fr/oauth/authorize?{urlencode(params)}"

# Update your views to use the new build_authorize_uri function
@require_http_methods(['GET', 'POST'])
def signup_v(request: HtmxHttpRequest) -> HttpResponse:
    logger.debug("== signup_v")
    context = {
        'authorize_uri': build_authorize_uri(FROMSIGNUP),
        'show_alerts': True,
        'request': request
    }
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been created! You are now able to log in.')
            context['form'] = AuthenticationForm()
            return render(request, 'users/login.html', context)
    else:
        form = UserRegisterForm()
    context['form'] = form

    return push_url(render(request, 'users/signup.html', context),'')

@require_http_methods(['GET', 'POST'])
def login_v(request: HtmxHttpRequest) -> HttpResponse:
    logger.debug("== login_v")
    template_name = "home/welcome.html"
    # if request.htmx:
    #     template_name += "#my_htmx_content"
    context = {
        'authorize_uri': build_authorize_uri(FROMLOGIN),
        'show_alerts': True,
        'request': request
    }
    if request.user and request.user.is_authenticated:
        logger.debug("== login_v : déjà identifié => home")
        return push_url(render(request, template_name, context),'')
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            user.profile.active = True
            login(request, user)
            context['request'] = request
            logger.debug("== login_v : identification ok")
            return push_url(render(request, template_name, context),'')
            # return render(request, 'home/welcome.html', context)
    else:
        form = AuthenticationForm()
    context['form'] = form
    template_name = "users/login.html"
    # if request.htmx:
    #     template_name += "#my_htmx_content"
    return push_url(render(request, template_name, context),'')
    # return render(request, 'users/login.html', context)



"""
Callback for Oauth2 logic
--
catches tmp_code, exchanges it for an access token, use that
token to get user informations
"""
@require_GET
def callback(request: HtmxHttpRequest) -> None:
    logger.debug("== callback")
    page_origin = request.GET.get('state')
    authorization_code = request.GET.get('code')
    if authorization_code is None:
        return HttpResponseBadRequest("Bad Request: Missing 'code' parameter")
    
    # exchange authorization code for access token
    o42 = Oauth42()
    token = o42.get_token(authorization_code)
    if token == None:
        messages.warning(request, f"Couldn't exchange code for access token.")
        return redirect('users:signup')

    # use token to request user data
    user_data = o42.get_user_data(token)
    if user_data == None:
        messages.warning(request, f'Error: Unable to login. Try signing-up. Probably 401 "Unauthorized"')
        return redirect('users:signup')
    username_42 = user_data.get('login')
    email_42 = user_data.get('email')

    # when user is in database
    if username_42 in str(User.objects.all()):
        known_user = User.objects.get(username=username_42)
        if known_user.profile.isstudent:
            known_user.profile.active = True
            login(request, known_user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('home:welcome')
        else:
            if page_origin == FROMLOGIN:
                messages.warning(request, "The account you're trying to connect to was created without 42intra. Please enter your credentials to log in.")
                return redirect('users:login')
            else:
                messages.warning(request, f'The username <strong>{username_42}</strong> already exists. Pleaser enter another one.')
                return redirect('users:signup')
    # when user is NOT in database
    if page_origin == FROMLOGIN:
        messages.info(request, "No corresponding account was found. Please sign-up first.")
        return redirect('users:signup')
    elif page_origin == FROMSIGNUP:
        newUser = User.objects.create_user(username_42, email_42)
        newUser.profile.isstudent = True
        newUser.profile.save()
        messages.success(request, f'Your account has been created! You are now able to log in.')
        return redirect('users:login')

@require_POST
def logout_v(request: HtmxHttpRequest) -> None:
    logger.debug("== logout_v")
    if request.method == 'POST':
        user = request.user
        user.profile.active = False
        user.profile.save()
        logout(request)
        messages.info(request, f'You have been logged out.')
        return redirect('users:login')

################################################################################

"""
Profile view of current user or another one
"""
@login_required(login_url='/users/login/?redirected=true')
def profile(request: HtmxHttpRequest, username: str) -> HttpResponse:
    logger.debug("== profile")
    context = {}
    try:
        displayed_user = User.objects.get(username=username)
    except:
        return render(request, '404.html', {
            'message': 'User not found',
            "show_alerts": True
        })
    if displayed_user:
        context['displayed_user'] = displayed_user
        context['username'] = displayed_user.username
        context['id'] = displayed_user.id
        context['email'] = displayed_user.email
        context['profile_img'] = displayed_user.profile.image.url
        context['wins'] = displayed_user.profile.wins
        context['losses'] = displayed_user.profile.losses
        context['active'] = displayed_user.profile.active
        context['description'] = displayed_user.profile.description
        context['all_users'] = User.objects.all()
        context['blocklist'] = displayed_user.profile.blocklist.all()

        try:
            friend_list = FriendList.objects.get(user=displayed_user)
        except FriendList.DoesNotExist:
            friend_list = FriendList(user=displayed_user)
            friend_list.save()
        friends = friend_list.friends.all()
        context['friends'] = friends

        # Fetch the latest matches for the displayed user
        latest_matches = LeaderboardEntry.objects.filter(user=displayed_user).order_by('-timestamp')[:10]
        context['latest_matches'] = latest_matches

        # Define template variables
        is_self = True
        is_friend = False
        request_sent = FriendRequestStatus.NO_REQUEST_SENT.value
        friend_requests = None
        user = request.user
        # Logged in but NOT looking at your own profile
        if user.is_authenticated and user != displayed_user:
            is_self = False
            if friends.filter(pk=user.id):
                is_friend = True
            else:
                is_friend = False
                # CASE1: Request has been sent from THEM to YOU: THEM_TO_YOU
                if get_friend_request_or_false(sender=displayed_user, receiver=user) != False:
                    request_sent = FriendRequestStatus.THEM_SENT_TO_YOU.value
                    context['pending_friend_request_id'] = get_friend_request_or_false(
                        sender=displayed_user,
                        receiver=user

django/templates/users/editprofile.html
{% extends 'home.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block script_body %}<script>document.title = '	Editing Profile'</script>{% endblock %}

{% block styles %}
{% endblock%}

{% block body %}
	<div>
		<h1 style="margin-bottom: 30px;">Edit Page</h1>
		<form hx-post="{% url 'users:profile_edit' %}" hx-encoding="multipart/form-data" hx-target="#app-body">
			{% csrf_token %}
			{{ u_form | crispy }}
			{{ p_form | crispy }}
			<button class="mt-3" style="display: inline-block;" type="submit">
				Update
			</button>	
		</form>
		<a href="/users/profile/{{ request.user.username }}/delete/">
			<button style="margin: 10px 0 0 0; padding: 5px 0;" class="btn_discrete text-danger">
				Delete your account
			</button>
		</a>
	</div>

{% endblock %}

django/templates/users/login.html
{% extends 'home.html' %}
{% load partials %}
{% load static %}
{% load crispy_forms_tags %}


{% block styles %}
<link rel="stylesheet" href="{% static 'css/users.css' %}">
{% endblock%}

{% block body %}

    <main class="login_box">
        <div class="login_img">
            <img src="{% get_media_prefix %}pong.webp" alt="pong image">
        </div>
        <div class="form">
            <div>
                <h1>Welcome Back</h1>
                <p>Not registered yet? <a href="{% url 'users:signup'%}">Sign up</a></p>
                <hr>
               <form hx-push-url="/" hx-post="{% url 'users:login' %}" hx-target="#app-body">
                     <div class="form_inputs">
                        {% csrf_token %}
                        {{ form | crispy }}
                    </div>
                    <div class="form_cta mt-4">
                        <button type="submit">Login</button>
                        <a class="row_custom" href="{{ authorize_uri }}">
                            <span>or use</span>
                            <img class="icon" src="{% static 'images/42-logo.svg' %}" alt="42 school logo">
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </main>
    <script>
        document.title = 'FT_TRANSCENDENCE';
        document.body.addEventListener('htmx:configRequest', (event) => {
            // Add the CSRF token to htmx requests
            var csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;
            event.detail.headers['X-CSRFToken'] = csrfToken;
        });
    </script>
{% endblock %}

django/templates/users/profile.html
{% extends 'home.html' %}
{% load partials %}
{% partialdef my_htmx_content inline %}
{% load static %}


{% block styles %}
	<link rel="stylesheet" href="{% static 'css/users.css' %}">
{% endblock %}

{% block body %}
	<div class="header d-flex">
		<img class="header_img" src="{{ profile_img }}" width="125px" height="125px" alt="profile picture">
		<div class="header_info">
			<div class="d-flex align-items-center">
				<h1 class="">@{{ username }}</h1>
				{% if username == request.user.username %}
					<a class="header_option edit" hx-get="{% url 'users:profile_edit' %}" hx-target="#app-root" hx-swap="innerHtml">
						<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
							<path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"/>
							</svg>
					</a>
				{% endif %}
				
				{% if active == True %}
					<div class="status_online"></div>
				{% else %}
					<div class="status_offline"></div>
				{% endif %}

				<div
					data-id="{{ id }}"
					{%if csrf_token %} data-csrf="{{ csrf_token }}" {%else%} data-csrf="{{ my_csrf }}" {%endif%}
					id="header_status_bar"
				>

				{% if request.user.is_authenticated %}
					{% if is_self == False %}
						<!-- Cancel Friend Request / Send Friend Request / Remove Friend -->
						{% if is_friend == False %}
							<!-- He/she sent you a request -->
							{% if request_sent == 0 %}
								<!-- ACCEPT -->
								<button
									onclick="acceptFriendRequest(
										'{{pending_friend_request_id}}',
										'header_status_bar'
										)"
									id="id_accept_request"
									class="btn_requests">
									Accept
								</button>
								<!-- IGNORE -->
								<button
									onclick='declineFriendRequest(
										"{{pending_friend_request_id}}",
										"header_status_bar",
									)'
									id="id_ignore_request"
									class="btn_requests">
									Ignore
								</button>
							{% endif %}
							<!-- You sent him/her a request -->
							{% if request_sent == 1 %}
								<!-- CANCEL -->
								<button
									data-next-url="{% url 'users:friend_request' %}"
									onclick="cancelFriendRequest(
										'{{ id }}',
										{% if csrf_token %} '{% csrf_token %}' {% else %} '{{my_csrf}}' {%endif%}
									)" 
									id="id_cancel_request_btn"
									class="btn_requests">
									Invitation sent
								</button>
							{% endif %}
							<!-- No requests has been sent -->
							{% if request_sent == -1 %}
								{% if request.user in displayed_user.profile.blocklist.all %}
									<!-- nothing to do -->
								{% else %}
									{% if displayed_user in request.user.profile.blocklist.all %}
										<!-- UNBLOCK -->
										<button
											onclick='blockUnblock("{{ id }}", "unblock")' 
											class="btn_requests">
											Unblock
										</button>
									{% else %}
										<!-- ADD FRIEND -->
										<button
											data-next-url="{% url 'users:friend_request_cancel' %}"
											onclick="sendFriendRequest(
												'{{ id }}', 
												{% if csrf_token %} '{% csrf_token %}' {% else %} '{{my_csrf}}' {%endif%},
											)"
											class="btn_requests"
											id="id_send_friend_request_btn">
											Add Friend
										</button>
										<!-- BLOCK -->
										<button
											onclick='blockUnblock("{{ id }}", "block")' 
											class="btn_requests">
											Block
										</button>
									{% endif %}
								{% endif %}
							{% endif %}
						{% endif %}
						{% if is_friend == True %}
								<!-- UNFRIEND -->
								<button
									onclick="removeFriend(
										'{{ id }}',
										{% if csrf_token %} '{% csrf_token %}' {% else %} '{{my_csrf}}' {%endif%},
									)"
									id="id_unfriend_btn" 
									class="btn_requests">
									Unfriend
								</button>
								<!-- MESSAGE -->
								<a hx-get="/chat/"
								    hx-target="#app-root"
                                    hx-push-url="true"
								>
									<button class="btn_requests">
											Message
									</button>
								</a>
								<!-- BLOCK -->
								<button 
									onclick='blockUnblock("{{ id }}", "block")' 
									class="btn_requests" 
									id="id_block_btn">
									Block
								</button>
						{% endif %} <!-- if a friend -->
					{% endif %} <!-- Not self -->

				{% endif %}
			
			</div> <!-- #action_bar -->

			</div>
			<p>{{description}}</p>
			<div class="d-flex header_score">
				<p class="mr-5 bs_v">wins: {{ wins }}</p>
				<p class="bs_l">losses: {{ losses }}</p>
			</div>
		</div>
	</div>
	<div class="d-flex">
		<section class="feed">
			<h3>Latest Matches</h3>
			{% if latest_matches %}
				<ul class="match-list">
					{% for match in latest_matches %}
						<li class="match-item">
							<div>
								<strong>Opponent:</strong>
								<a 
									hx-get="/users/profile/{{ match.opponent.username }}"
									hx-target="#app-root"
									hx-push-url="true">
									{{ match.opponent.username }}
								</a>
							</div>
							<div>
								<strong>Score:</strong> {{ match.player_score }} - {{ match.opponent_score }}
							</div>
							<div>
								<strong>Date:</strong> {{ match.timestamp|date:"Y-m-d H:i" }}
							</div>
						</li>
					{% endfor %}
				</ul>
			{% else %}
				<p>No matches found.</p>
			{% endif %}
		</section>
		
		{% if request.user.is_authenticated and is_self == True %}
		<aside class="sidebar ms-auto">

			<!-- Friends List -->
			<h5>Friends ({{ friends | length }})</h5>
			<div class="users_list">
				{% for f in friends %}
				<div class="user_card">
					<a 
						hx-get="/users/profile/{{ f.username }}"
						hx-target="#app-root"
						hx-push-url="true">
						<img
							src="{{ f.profile.image.url }}"
							width="48px"
							height="48px"
							alt="profile picture"
						>
					</a>
					<p>{{ f.username }}</p>
				</div>
				{% endfor %}
			</div>

			<!-- Friend Requests -->
			<h5>Friend Requests</h5>
			<div 
				data-id="{{id}}"
				{%if csrf_token %} data-csrf="{{ csrf_token }}" {%else%} data-csrf="{{ my_csrf }}" {%endif%}
				id="widget_status_bar"
			>
			{% if request.user.is_authenticated and is_self == True%}
				{% for request in friend_requests %}
				<div class="request_card">
					<a 
						hx-get="/users/profile/{{ request.sender.username}}"
						hx-target="#app-root"
						hx-push-url="true">
						<img src="{{ request.sender.profile.image.url }}" width="48px" height="48px" alt="profile picture">
					</a>
					<div>
						<p><b>{{ request.sender | capfirst }}</b></p>
						<div>
							<button
								onclick="acceptFriendRequest(
									'{{request.id}}',
									'widget_status_bar',
								)"
								class="btn_requests">
								Confirm
							</button>
							<button 
								onclick='declineFriendRequest(
									"{{request.id}}",
									"widget_status_bar",
								)' 
								class="btn_discrete btn_passive">
								Ignore
							</button>
						</div>
					</div>
				</div>
				{% endfor %}
			{% endif %}
			</div>

			<!-- All Users -->
			<h5>All Users</h5>
			<div class="users_list">

				{% for usr in all_users %}
					{% if usr != request.user and usr not in friends and usr not in blocklist %}
						<div class="user_card">
							<a 
								hx-get="/users/profile/{{ usr.username }}"
								hx-target="#app-root"
								hx-push-url="true">
								<img src="{{ usr.profile.image.url }}" width="48px" height="48px" alt="profile picture">
							</a>
							<p>{{ usr.username }}</p>
						</div>
					{% endif %}
				{% endfor %}
	
			</div>

			<!-- Blocked -->
			<h5>Blocked</h5>
			<div class="users_list">
			{% if request.user.is_authenticated and is_self == True %}

				{% if blocklist|length > 0 %}

					{% for blocked_user in blocklist %}
					<div class="user_card">
						<a 
							hx-get="/users/profile/{{ blocked_user.username }}"
							hx-target="#app-root"
							hx-push-url="true">
							<img src="{{ blocked_user.profile.image.url }}" width="48px" height="48px" alt="profile picture">
						</a>
						<p>{{ blocked_user.username }}</p>
					</div>
					{% endfor %}

				{% endif %}
			
			{% endif %}
			</div>

		</aside>
		{% endif%}
	</div>

{% endblock %}

{% block script_body %}
    <script type="text/javascript">document.title = 'Profile';</script>
	<script type="text/javascript" src="{% static 'js/friendrequests.js' %}"></script>
{% endblock %}

{% endpartialdef %}

django/templates/users/signup.html
{% extends 'home.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block script_body %}<script>document.title = '	FT_TRANSCENDENCE'</script>{% endblock %}

{% block styles %}
{% endblock %}

{% block body %}
	<div class="signin_box">
		<div>
			<h1>Get Started</h1>
			<p>Already have an account? <a href="{% url 'users:login' %}">Login</a></p>
			<hr>
			<div>
				<form hx-post="{% url 'users:signup' %}" hx-target="#app-body" hx-push-url="true">
					<div class="signin_form_inputs">
						{% csrf_token %}
						{{ form | crispy }}	
					</div>
					<div class="form_cta">
						<button type="submit">Register</button>
						<a class="row_custom" href="{{ authorize_uri }}">
                            <span>or use</span>
                            <img class="icon" src="{% static 'images/42-logo.svg' %}" alt="42 school logo">
                        </a>
					</div>
				</form>
				{% if form.errors %}
					<p>Please try again.</p>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}